### ISSUE TITLE
Can't not disable enchantments!

### ISSUE THREAD

**Issue by PhuongBlu** [Dzious/EnchantControl#16]
### Describe the bug

___

### How to reproduce the bug ?
1. setup in config file is: 
enchantments: 
minecraft: 
silk_touch: 0
2.
3.

___

### What is your EnchantControl version?

1.2.4
___

### What is your spigot/craftbukkit version?

Paper 1.16.5
___

#### Please use [Pastebin.com] to share the following files

**These files are essential to understand and resolve the bugs. If you do not provide us these files, your issue ticket will most likely be deleted and you will be asked to submit an other one.**

1. Your full server startup from the logs\latest.log : https://pastebin.com/PgWWZ2gN
2. Your EnchantControl config.yml : https://pastebin.com/f2qphejC
3. Your log's error : https://pastebin.com/Ttu8QsBZ

[Pastebin.com]: https://pastebin.com

**Comment by TheZennou** [comment]
Most likely you have incorrect spacing in the config. Each enchant disable entry needs to have exactly 8 spaces. Below I will attach my config as an example, feel free to just copy it and make the modifications you need.

```
# Enchantment that have to be controlled. 
# Enchantment that aren't there will be kept on their default values
# enchantments.<sourceName>.<enchantmentName>: <maxLevel>
# Source Name       is the origin of the enchantments.      Example : minecraft
# Enchantment Name  is the name of the enchantments.        Example : protection
# Max Level         is the maximum enchantment level
#                   you want on your server. To disable
#                   an enchantment set level to 0.
#                   level range is between 0-2147483647     Example : 4
enchantments:
    minecraft:
        bane_of_arthropods: 0
        blast_protection: 0
        depth_strider: 0
        fire_aspect: 0
        fire_protection: 0
        flame: 0
        impaling: 0
        knockback: 0
        loyalty: 0
        multishot: 0
        piercing: 0
        power: 0
        projectile_protection: 0
        protection: 0
        punch: 0
        quick_charge: 0
        sharpness: 0
        smite: 0
        thorns: 0
        fortune: 1
        looting: 1
```
